### ISSUE TITLE
How to focus the dom on launch?

### ISSUE THREAD

**Issue by caph1993** [flexxui/webruntime#20]
After launching a flexx app with `app.launch('app')`, the document seems not to be focused ( `document.hasFocus()` returns false).
 
Is it possible to have the DOM focused on launch? Some functions, such as focusing particular elements rely on the DOM being focused on the first place.

**Comment by almarklein** [comment]
No, unfortunately this is not possible. The app is basically a browser window, and browsers don't allow the JS to focus the window.

**Comment by almarklein** [comment]
I'm sorry that I have to answer all your questions with "no" :)
