### ISSUE TITLE
Could not detect a suitable backend among ['firefox-browser']

### ISSUE THREAD

**Issue by LewisNeal** [flexxui/webruntime#23]
Running the example with webruntime v0.5.7
rt = launch('http://xkcd.com', 'firefox-browser') 
gives error:
```
[snip] _\webruntime\__init__.py", line 200, in launch
    raise ValueError('Could not detect a suitable backend among %r.' % runtimes)

ValueError: Could not detect a suitable backend among ['firefox-browser']._
```
and choosing chrome:
```
    [snip] _\webruntime\__init__.py", line 200, in launch
    raise ValueError('Could not detect a suitable backend among %r.' % runtimes)

ValueError: Could not detect a suitable backend among ['googlechrome-browser', 'chromium-browser']._
```
The only browser which launches is edge.

**Comment by almarklein** [comment]
It looks like Webruntime is not able to find Firefox nor Chrome on your system. What platform are you on? It could be that we need an extra line [here](https://github.com/flexxui/webruntime/blob/master/webruntime/_firefox.py#L134).

**Comment by LewisNeal** [comment]
I'm running Python 3.8.4, on Windows 10 64 (build 10.0.18362) SP0
Firefox and Chrome have both worked previously with webruntime.

**Comment by almarklein** [comment]
Could you check the location of firefox and chrome, and see if we are missing some paths? See e.g. #24 that adds paths for Linux and MacOS.

**Comment by LewisNeal** [comment]
Location of firefox: "C:\Program Files\Firefox Nightly\firefox.exe"
I have been using nightly for years.

**Comment by almarklein** [comment]
Would you mind submitting a PR to add that path [here](https://github.com/flexxui/webruntime/blob/master/webruntime/_firefox.py#L134)? Otherwise I'll get to it eventually :)

**Comment by LewisNeal** [comment]
See PR https://github.com/flexxui/webruntime/pull/26
