### ISSUE TITLE
Unable to launch a webruntime on Win10 x64 Python 3.6

### ISSUE THREAD

**Issue by Semnodime** [flexxui/webruntime#3]
I know that the whole project remains in Alpha so far and is under active change currently.
Since I would like to try out flexx already, could you please guide me how to successfully launch a (standalone) app?

**1. Installed flexx over latest master**
------------------------------------------------

The module flexx.webruntime was not available after installing flexx the way described in the flexxun/flexx github [README](https://github.com/flexxui/flexx/blob/master/README.md)
> pip install https://github.com/flexxui/flexx/archive/master.zip
> Successfully installed flexx-0.4.2.dev0 webruntime-0.5.2

**2. Installed webruntime directly**
------------------------------------------------
> pip install webruntime
> Successfully installed webruntime-0.5.2

The webruntime does not seem to work when installed standalone either:
![image](https://user-images.githubusercontent.com/19511852/38769435-6c28a1a6-4003-11e8-8fdf-3a62699ff6db.png)
![image](https://user-images.githubusercontent.com/19511852/38769436-6c38c090-4003-11e8-9b4f-91b14868032a.png)

**3. Installed flexx over pip** 
------------------------------------------------
> pip install flexx
> Successfully installed flexx-0.4.1
![image](https://user-images.githubusercontent.com/19511852/38769654-b1d354c8-4006-11e8-95c7-c169399afbfc.png)
![image](https://user-images.githubusercontent.com/19511852/38769667-d2921d66-4006-11e8-84a2-cb2fd4a520e7.png)

I cannot use 'app' as webruntime

EDIT:
---------------------
Somewhere I found the list of available runtimes as I dug into the code and tested all of them:

![image](https://user-images.githubusercontent.com/19511852/38770928-781a877e-401a-11e8-836c-e06e31608fe7.png)
![image](https://user-images.githubusercontent.com/19511852/38770940-a628d83c-401a-11e8-9bb1-2d5e59601572.png)

So **XulRuntime**, **ChromeAppRuntime** and **Browser(s)** seem to work for me.

Maybe I have missed where you mentioned how to _select the "correct" runtime_ in the docs,
please let me know if I missed it or if you decided to insert this piece of information.

**Comment by Semnodime** [comment]
Also, XulRuntime closes without a while-1-loop at the end of the programm, while ChromeAppRuntime does not.

**Comment by almarklein** [comment]
Remove the `rt.close()` That closes the runtime, which you probably do not want to do until you're done.

**Comment by Semnodime** [comment]
The code snapshots above addresses only

- the issue that the module flexx.webruntime was not available after installing flexx the way described in the flexxun/flexx github README

- and the issue that the webruntime 'app' was not recognized and I needed to dig into the source code to find working strings as webruntime type.

But the closing of the runtime occured when the code in my screenshot (below my heading «EDIT») was executed which does not contain an rt.close() (it is commented out)

**Comment by almarklein** [comment]
Ah, now I see your point. Thanks for the clarification.

The example in the readme was wrong, it should say `from webruntime import launch` not `from flexx.webruntime import launch`. Also the latest version of Flexx is really old, it does not know about the "app" runtime yet.

Thanks for the issue report!
